# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remainder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_lat', models.CharField(max_length=64)),
                ('src_lng', models.CharField(max_length=64)),
                ('dest_lat', models.CharField(max_length=64)),
                ('dest_lng', models.CharField(max_length=64)),
                ('dest_time', models.CharField(max_length=64)),
                ('reminder_time', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
